name: update_db
env:
  URI: ${{secrets.URI}}
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '52 18 * * *'
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: pip3 install -r requirements.txt
      - run: python3 data.py
      - run: echo 'Done'
